---
layout: cv
title: Isaiah Carrin's CV
---
# Isaiah Carrin
Computer Science major, machine learning emphasis. 

<div id="webaddress">
<a href="https://github.com/iCarrin">iCarrin github</a>
|<a href="www.linkedin.com/in/isaiah-carrin">Isaiah Carrin Linkden</a>
</div>


## Currently
Finishing a bachelors 

### Specialized in

React, Python, C#, and Cabinetry

## Education

`2024-Present`  
__Carpet Cleaner Technician__, East Idaho Carpet Cleaners, Idaho Falls, ID  

`2024`  
__Pest Control Route Manager__, Elevate Pest Control, Rexburg, ID  

`2024`  
__HVAC Installer Apprentice__, IF Ductless Heating & Air, Rexburg, ID  

`2022-2024`  
__Warehouse Associate / Receptionist__, Palmer's Metal Mart, North Logan, UT  

`2022`  
__Carpenter / Painter__, Westates Construction, Logan, UT  

`2022`  
__Carpet Technician__, Zerorez, Logan, UT  

`2022`  
__Manufacturing Associate__, The Stow Company, Rexburg, ID  

`2021-2022`  
__Hardlines Team Member__, Walmart, Rexburg, ID  

`2021`  
__Temp Operation Worker__, IES Custom Staffing, Idaho Falls, ID  

`2021`  
__Mover__, College Movers, Rexburg, ID  

`2021`  
__Sales Associate__, Progrexion / Credit.com, Rexburg, ID  

`2019-2020`  
__Cabinet Maker__, Clayton Fixtures, Ellenwood, GA  

`2017-2019`  
__Missionary__, The Church of Jesus Christ of Latter-day Saints, Anaheim, CA  

`2016-2017`  
__Sales Associate__, rue21, Stockbridge, GA  



<!-- ### Footer

Last updated: May 2013 -->